[plugin]
id = "mcp-compiler-plugin"
class = "io.ballerina.stdlib.mcp.plugin.McpCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/mcp-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-@ballerinaToOpenApiVersion.version@.jar"
