[package]
org = "ballerina"
name = "mcp_crypto_client_demo"
version = "0.1.0"
distribution = "2201.12.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mcp"
version = "0.4.2"
repository = "local"
